/**
 * Colección Masiva de Datos Semilla (Preset Seed Data) para CampFit.
 * Contiene bibliotecas profesionales de ejercicios, comidas, dietas completas y rutinas.
 *
 * @module devtools/seedData
 */

import type { ExerciseTemplate, MealTemplate, DietTemplate, WorkoutTemplate } from './types';

/** Plantillas de Ejercicios por Categoría (20+ Ejercicios) */
export const SEED_EXERCISES: Omit<ExerciseTemplate, 'id'>[] = [
  // Pecho
  {
    name: 'Press de Banca Plano con Barra',
    category: 'Pecho',
    defaultSets: 4,
    defaultReps: 8,
    defaultRestTime: '90s',
    description: 'Ejercicio básico multiarticular para pectoral mayor, deltoides anterior y tríceps.',
    videoUrl: 'https://www.youtube.com/watch?v=rT7DgCr-3pg',
    isPreset: true,
    source: 'system',
  },
  {
    name: 'Press Inclinado con Mancuernas',
    category: 'Pecho',
    defaultSets: 4,
    defaultReps: 10,
    defaultRestTime: '75s',
    description: 'Enfocado en el haz clavicular (pecho superior). Mantener codos en ángulo de 45°.',
    videoUrl: 'https://www.youtube.com/watch?v=8iPEnn-ltC8',
    isPreset: true,
    source: 'system',
  },
  {
    name: 'Aperturas con Polea (Crossover)',
    category: 'Pecho',
    defaultSets: 3,
    defaultReps: 12,
    defaultRestTime: '60s',
    description: 'Aislamiento de pectoral en tensión constante con contracción al centro.',
    videoUrl: 'https://www.youtube.com/watch?v=taI4XduLpTk',
    isPreset: true,
    source: 'system',
  },

  // Espalda
  {
    name: 'Peso Muerto Convencional',
    category: 'Espalda',
    defaultSets: 4,
    defaultReps: 6,
    defaultRestTime: '120s',
    description: 'Ejercicio dominante de cadera para dorsal ancho, erectores espinales y glúteos.',
    videoUrl: 'https://www.youtube.com/watch?v=op9kVnSso6Q',
    isPreset: true,
    source: 'system',
  },
  {
    name: 'Dominadas Pronadas',
    category: 'Espalda',
    defaultSets: 4,
    defaultReps: 8,
    defaultRestTime: '90s',
    description: 'Tracción vertical para desarrollo del dorsal ancho. Escápulas deprimidas al subir.',
    videoUrl: 'https://www.youtube.com/watch?v=eGo4IYlbE5g',
    isPreset: true,
    source: 'system',
  },
  {
    name: 'Remo con Barra Horizontal',
    category: 'Espalda',
    defaultSets: 4,
    defaultReps: 10,
    defaultRestTime: '90s',
    description: 'Tracción horizontal para densidad de espalda (trapecios, romboides y dorsal).',
    videoUrl: 'https://www.youtube.com/watch?v=VKFeB7jy8zE',
    isPreset: true,
    source: 'system',
  },
  {
    name: 'Jalón al Pecho Neutro en Polea',
    category: 'Espalda',
    defaultSets: 3,
    defaultReps: 12,
    defaultRestTime: '75s',
    description: 'Alternativa guiada a dominadas enfocada en dorsal ancho con menor esfuerzo de grip.',
    videoUrl: 'https://www.youtube.com/watch?v=CAwf7n6Luuc',
    isPreset: true,
    source: 'system',
  },

  // Piernas
  {
    name: 'Sentadilla Trasera con Barra (Back Squat)',
    category: 'Piernas',
    defaultSets: 4,
    defaultReps: 8,
    defaultRestTime: '120s',
    description: 'Ejercicio básico para cuadriceps, glúteos y aductores. Romper el paralelo.',
    videoUrl: 'https://www.youtube.com/watch?v=ultWZbUMPL8',
    isPreset: true,
    source: 'system',
  },
  {
    name: 'Prensa de Piernas 45°',
    category: 'Piernas',
    defaultSets: 4,
    defaultReps: 12,
    defaultRestTime: '90s',
    description: 'Trabajo guiado e intenso para cuadriceps reduciendo la carga sobre la columna.',
    videoUrl: 'https://www.youtube.com/watch?v=IZxyjW7MPJQ',
    isPreset: true,
    source: 'system',
  },
  {
    name: 'Zancadas Caminando con Mancuernas',
    category: 'Piernas',
    defaultSets: 3,
    defaultReps: 12,
    defaultRestTime: '60s',
    description: 'Trabajo unilateral para estabilizadores de rodilla, glúteo mayor y cuadriceps.',
    videoUrl: 'https://www.youtube.com/watch?v=D7KaRcUTQeE',
    isPreset: true,
    source: 'system',
  },
  {
    name: 'Peso Muerto Rumano (RDL)',
    category: 'Piernas',
    defaultSets: 4,
    defaultReps: 10,
    defaultRestTime: '90s',
    description: 'Enfocado en isquiotibiales y glúteos mediante flexión activa de cadera.',
    videoUrl: 'https://www.youtube.com/watch?v=JCXUYuzwNrM',
    isPreset: true,
    source: 'system',
  },
  {
    name: 'Hip Thrust con Barra en Banco',
    category: 'Piernas',
    defaultSets: 4,
    defaultReps: 10,
    defaultRestTime: '90s',
    description: 'Ejercicio número 1 para aislamiento e hipertrofia del glúteo mayor.',
    videoUrl: 'https://www.youtube.com/watch?v=LM8XHLYJoYs',
    isPreset: true,
    source: 'system',
  },

  // Hombros
  {
    name: 'Press Militar de Pie con Barra',
    category: 'Hombros',
    defaultSets: 4,
    defaultReps: 8,
    defaultRestTime: '90s',
    description: 'Empuje vertical para deltoides anterior, deltoides medio y estabilidad de core.',
    videoUrl: 'https://www.youtube.com/watch?v=2yjwXTZQDDI',
    isPreset: true,
    source: 'system',
  },
  {
    name: 'Elevaciones Laterales con Mancuernas',
    category: 'Hombros',
    defaultSets: 4,
    defaultReps: 15,
    defaultRestTime: '60s',
    description: 'Aislamiento del deltoides lateral para amplitud de hombros.',
    videoUrl: 'https://www.youtube.com/watch?v=3VcKaXpzqRo',
    isPreset: true,
    source: 'system',
  },
  {
    name: 'Pájaro en Polea / Facepulls',
    category: 'Hombros',
    defaultSets: 3,
    defaultReps: 15,
    defaultRestTime: '60s',
    description: 'Salud articular de hombro y desarrollo del deltoides posterior y manguito rotador.',
    videoUrl: 'https://www.youtube.com/watch?v=rep-qVOkqgk',
    isPreset: true,
    source: 'system',
  },

  // Brazos
  {
    name: 'Curl de Bíceps Alterno con Mancuernas',
    category: 'Brazos',
    defaultSets: 3,
    defaultReps: 12,
    defaultRestTime: '60s',
    description: 'Flexión de codo con supinación activa de muñeca.',
    videoUrl: 'https://www.youtube.com/watch?v=ykJmrZ5v0Oo',
    isPreset: true,
    source: 'system',
  },
  {
    name: 'Fondos en Paralelas para Tríceps',
    category: 'Brazos',
    defaultSets: 3,
    defaultReps: 10,
    defaultRestTime: '75s',
    description: 'Autocarga para tríceps braquial y porción inferior del pecho.',
    videoUrl: 'https://www.youtube.com/watch?v=2z8JmcrW-As',
    isPreset: true,
    source: 'system',
  },

  // Core & Cardio
  {
    name: 'Plancha Abdominal Isometrica',
    category: 'Core',
    defaultSets: 3,
    defaultReps: 45,
    defaultRestTime: '45s',
    description: 'Estabilidad central del núcleo en posición neutra.',
    videoUrl: 'https://www.youtube.com/watch?v=pSHjTRCQxIw',
    isPreset: true,
    source: 'system',
  },
  {
    name: 'Rueda Abdominal (Ab-Wheel Rollout)',
    category: 'Core',
    defaultSets: 3,
    defaultReps: 10,
    defaultRestTime: '60s',
    description: 'Anti-extensión lumbar avanzada para recto abdominal y transverso.',
    videoUrl: 'https://www.youtube.com/watch?v=rqiTPdK1c_I',
    isPreset: true,
    source: 'system',
  },
  {
    name: 'Sprints HIIT en Cinta o Pista',
    category: 'Cardio',
    defaultSets: 8,
    defaultReps: 30,
    defaultRestTime: '60s',
    description: '30s sprint máximo + 60s descanso activo para quema de grasa y VO2Max.',
    videoUrl: 'https://www.youtube.com/watch?v=cZnsLVArIt8',
    isPreset: true,
    source: 'system',
  },
];

/** Plantillas de Comidas (16+ Comidas) */
export const SEED_MEALS: Omit<MealTemplate, 'id'>[] = [
  {
    name: 'Desayuno Proteico de Avena y Claras',
    type: 'breakfast',
    calories: 450,
    protein: 35,
    carbs: 55,
    fat: 8,
    description: '60g avena integrales, 200ml claras de huevo, 100g frutos rojos y 1 scoop proteína.',
    isPreset: true,
    source: 'system',
  },
  {
    name: 'Tostadas Integrales con Pavo y Aguacate',
    type: 'breakfast',
    calories: 380,
    protein: 24,
    carbs: 38,
    fat: 14,
    description: '2 rebanadas pan 100% integral, 80g pechuga de pavo baja en sal y 50g aguacate.',
    isPreset: true,
    source: 'system',
  },
  {
    name: 'Porridge Vegano con Semillas de Chía',
    type: 'breakfast',
    calories: 420,
    protein: 22,
    carbs: 58,
    fat: 12,
    description: 'Avena, proteína de guisante, leche de almendras, semillas de chía y arándanos.',
    isPreset: true,
    source: 'system',
  },
  {
    name: 'Huevos Revueltos Keto con Espinacas y Q. Feta',
    type: 'breakfast',
    calories: 410,
    protein: 28,
    carbs: 5,
    fat: 32,
    description: '3 huevos enteros, 50g queso feta, 100g espinacas salteadas en mantequilla ghee.',
    isPreset: true,
    source: 'system',
  },

  {
    name: 'Almuerzo Fitness Pollo, Boniato y Brócoli',
    type: 'lunch',
    calories: 550,
    protein: 48,
    carbs: 60,
    fat: 10,
    description: '180g pechuga de pollo, 200g boniato al horno, 150g brócoli con aove.',
    isPreset: true,
    source: 'system',
  },
  {
    name: 'Almuerzo Ternera Magra con Arroz Basmati',
    type: 'lunch',
    calories: 620,
    protein: 52,
    carbs: 68,
    fat: 14,
    description: '180g solomillo de ternera magra, 200g arroz basmati y ensalada verde.',
    isPreset: true,
    source: 'system',
  },
  {
    name: 'Bowl Vegano de Tofu y Quinoa',
    type: 'lunch',
    calories: 520,
    protein: 32,
    carbs: 62,
    fat: 16,
    description: '200g tofu firme marinado, 180g quinoa cocida, edamame, aguacate y zanahoria.',
    isPreset: true,
    source: 'system',
  },
  {
    name: 'Ensalada Keto de Pollo, Bacon y Aguacate',
    type: 'lunch',
    calories: 580,
    protein: 42,
    carbs: 8,
    fat: 42,
    description: 'Pechuga a la plancha, 2 lonchas bacon crujiente, 100g aguacate y aderezo aove.',
    isPreset: true,
    source: 'system',
  },

  {
    name: 'Merienda Yogurt Griego y Nueces',
    type: 'snack',
    calories: 280,
    protein: 20,
    carbs: 15,
    fat: 16,
    description: '200g yogurt griego 0%, 20g nueces de california y 1 manzana verde.',
    isPreset: true,
    source: 'system',
  },
  {
    name: 'Batido Post-Entreno Proteína y Plátano',
    type: 'snack',
    calories: 310,
    protein: 32,
    carbs: 38,
    fat: 4,
    description: '1 scoop Whey Isolate, 1 plátano maduro y 250ml leche de almendras.',
    isPreset: true,
    source: 'system',
  },
  {
    name: 'Hummus con Bastones de Zanahoria y Tortitas',
    type: 'snack',
    calories: 260,
    protein: 10,
    carbs: 34,
    fat: 10,
    description: '80g hummus garbanzo, bastones de zanahoria fresca y 2 tortitas de maíz.',
    isPreset: true,
    source: 'system',
  },

  {
    name: 'Cena Salmón a la Plancha y Espárragos',
    type: 'dinner',
    calories: 490,
    protein: 42,
    carbs: 18,
    fat: 26,
    description: '170g lomo de salmón fresco, espárragos trigueros y 100g quinoa.',
    isPreset: true,
    source: 'system',
  },
  {
    name: 'Cena Tortilla de Atún y Ensalada Mixta',
    type: 'dinner',
    calories: 410,
    protein: 38,
    carbs: 12,
    fat: 22,
    description: '2 huevos + 2 claras, 1 lata atún natural, ensalada de canónigos y tomate.',
    isPreset: true,
    source: 'system',
  },
  {
    name: 'Cena Bacalao al Horno con Verduras Salteadas',
    type: 'dinner',
    calories: 360,
    protein: 40,
    carbs: 14,
    fat: 14,
    description: '200g lomo de bacalao, calabacín, pimiento rojo y cebolla con aove.',
    isPreset: true,
    source: 'system',
  },
];

/** Plantillas de Dietas Completas (6 Dietas) */
export const SEED_DIETS: Omit<DietTemplate, 'id'>[] = [
  {
    name: 'Dieta de Definición / Pérdida de Grasa (2000 kcal)',
    type: 'normal',
    somatotype: 'endomorph',
    totalCalories: 2000,
    description: 'Plan normo/hipocalórico rico en proteína (180g) para preservar masa muscular en déficit.',
    isPreset: true,
    source: 'system',
    meals: [
      {
        id: 'm-def-1',
        name: 'breakfast',
        description: 'Desayuno Proteico de Avena y Claras',
        calories: 450,
        protein: 35,
        carbs: 55,
        fat: 8,
        order: 1,
      },
      {
        id: 'm-def-2',
        name: 'lunch',
        description: 'Almuerzo Fitness Pollo, Boniato y Brócoli',
        calories: 550,
        protein: 48,
        carbs: 60,
        fat: 10,
        order: 2,
      },
      {
        id: 'm-def-3',
        name: 'snack',
        description: 'Merienda Yogurt Griego y Nueces',
        calories: 280,
        protein: 20,
        carbs: 15,
        fat: 16,
        order: 3,
      },
      {
        id: 'm-def-4',
        name: 'dinner',
        description: 'Cena Salmón a la Plancha y Espárragos',
        calories: 490,
        protein: 42,
        carbs: 18,
        fat: 26,
        order: 4,
      },
    ],
  },
  {
    name: 'Dieta de Volumen / Ganancia Muscular (3000 kcal)',
    type: 'advanced',
    somatotype: 'ectomorph',
    totalCalories: 3000,
    description: 'Plan hipercalórico enfocado en crecimiento muscular magro con alto aporte de carbohidratos.',
    isPreset: true,
    source: 'system',
    meals: [
      {
        id: 'm-vol-1',
        name: 'breakfast',
        description: 'Desayuno XL: Avena, claras, crema de cacahuete, plátano.',
        calories: 750,
        protein: 45,
        carbs: 95,
        fat: 20,
        order: 1,
      },
      {
        id: 'm-vol-2',
        name: 'lunch',
        description: 'Almuerzo Ternera Magra con Arroz Basmati',
        calories: 820,
        protein: 58,
        carbs: 90,
        fat: 22,
        order: 2,
      },
      {
        id: 'm-vol-3',
        name: 'snack',
        description: 'Batido Post-Entreno Proteína y Plátano',
        calories: 600,
        protein: 42,
        carbs: 75,
        fat: 14,
        order: 3,
      },
      {
        id: 'm-vol-4',
        name: 'dinner',
        description: 'Cena: Pechuga de pavo, patata al horno y ensalada.',
        calories: 630,
        protein: 48,
        carbs: 75,
        fat: 16,
        order: 4,
      },
    ],
  },
  {
    name: 'Dieta Vegetariana Fitness (2200 kcal)',
    type: 'normal',
    somatotype: 'mesomorph',
    totalCalories: 2200,
    description: 'Plan ovo-lacto-vegetariano optimizado con proteína vegetal completa (tofu, quinoa, legumbres).',
    isPreset: true,
    source: 'system',
    meals: [
      {
        id: 'm-veg-1',
        name: 'breakfast',
        description: 'Porridge Vegano con Semillas de Chía',
        calories: 420,
        protein: 22,
        carbs: 58,
        fat: 12,
        order: 1,
      },
      {
        id: 'm-veg-2',
        name: 'lunch',
        description: 'Bowl Vegano de Tofu y Quinoa',
        calories: 520,
        protein: 32,
        carbs: 62,
        fat: 16,
        order: 2,
      },
      {
        id: 'm-veg-3',
        name: 'snack',
        description: 'Hummus con Bastones de Zanahoria y Tortitas',
        calories: 260,
        protein: 10,
        carbs: 34,
        fat: 10,
        order: 3,
      },
      {
        id: 'm-veg-4',
        name: 'dinner',
        description: 'Cena Bacalao al Horno o Tofu marinado con Verduras',
        calories: 460,
        protein: 40,
        carbs: 25,
        fat: 20,
        order: 4,
      },
    ],
  },
  {
    name: 'Dieta Keto / Low-Carb Adaptada (1800 kcal)',
    type: 'advanced',
    somatotype: 'endomorph',
    totalCalories: 1800,
    description: 'Plan cetogénico estructurado (<30g carbs/día) para máxima oxidación de grasa.',
    isPreset: true,
    source: 'system',
    meals: [
      {
        id: 'm-keto-1',
        name: 'breakfast',
        description: 'Huevos Revueltos Keto con Espinacas y Q. Feta',
        calories: 410,
        protein: 28,
        carbs: 5,
        fat: 32,
        order: 1,
      },
      {
        id: 'm-keto-2',
        name: 'lunch',
        description: 'Ensalada Keto de Pollo, Bacon y Aguacate',
        calories: 580,
        protein: 42,
        carbs: 8,
        fat: 42,
        order: 2,
      },
      {
        id: 'm-keto-3',
        name: 'snack',
        description: 'Merienda: Puñado de almendras y queso manchego curado',
        calories: 300,
        protein: 14,
        carbs: 4,
        fat: 26,
        order: 3,
      },
      {
        id: 'm-keto-4',
        name: 'dinner',
        description: 'Cena Salmón a la Plancha con Espárragos Trigueros',
        calories: 510,
        protein: 44,
        carbs: 5,
        fat: 34,
        order: 4,
      },
    ],
  },
  {
    name: 'Dieta Recomposición y Mantenimiento (2400 kcal)',
    type: 'normal',
    somatotype: 'mesomorph',
    totalCalories: 2400,
    description: 'Plan isocalórico para perder grasa y ganar músculo simultáneamente.',
    isPreset: true,
    source: 'system',
    meals: [
      {
        id: 'm-rec-1',
        name: 'breakfast',
        description: 'Tostadas Integrales con Pavo y Aguacate',
        calories: 380,
        protein: 24,
        carbs: 38,
        fat: 14,
        order: 1,
      },
      {
        id: 'm-rec-2',
        name: 'lunch',
        description: 'Almuerzo Ternera Magra con Arroz Basmati',
        calories: 620,
        protein: 52,
        carbs: 68,
        fat: 14,
        order: 2,
      },
      {
        id: 'm-rec-3',
        name: 'snack',
        description: 'Batido Post-Entreno Proteína y Plátano',
        calories: 310,
        protein: 32,
        carbs: 38,
        fat: 4,
        order: 3,
      },
      {
        id: 'm-rec-4',
        name: 'dinner',
        description: 'Cena Salmón a la Plancha y Espárragos',
        calories: 490,
        protein: 42,
        carbs: 18,
        fat: 26,
        order: 4,
      },
    ],
  },
];

/** Plantillas de Rutinas de Entrenamiento (5 Rutinas) */
export const SEED_WORKOUTS: Omit<WorkoutTemplate, 'id'>[] = [
  {
    name: 'Rutina FullBody Principiante (3 Días)',
    difficulty: 'beginner',
    description: 'Rutina de cuerpo completo diseñada para principiantes. Frecuencia 3 con ejercicios básicos.',
    isPreset: true,
    source: 'system',
    exercises: [
      {
        id: 'ex-fb-1',
        name: 'Sentadilla Trasera con Barra (Back Squat)',
        sets: 3,
        reps: 10,
        restTime: '90s',
        videoUrl: 'https://www.youtube.com/watch?v=ultWZbUMPL8',
        description: 'Espalda recta y codos alineados.',
        order: 1,
        dayOfWeek: 1,
      },
      {
        id: 'ex-fb-2',
        name: 'Press de Banca Plano con Barra',
        sets: 3,
        reps: 10,
        restTime: '90s',
        videoUrl: 'https://www.youtube.com/watch?v=rT7DgCr-3pg',
        description: 'Retracción escapular activa.',
        order: 2,
        dayOfWeek: 1,
      },
      {
        id: 'ex-fb-3',
        name: 'Remo con Barra Horizontal',
        sets: 3,
        reps: 10,
        restTime: '90s',
        videoUrl: 'https://www.youtube.com/watch?v=VKFeB7jy8zE',
        description: 'Tirar de la barra hacia el ombligo.',
        order: 3,
        dayOfWeek: 1,
      },
      {
        id: 'ex-fb-4',
        name: 'Press Militar de Pie con Barra',
        sets: 3,
        reps: 10,
        restTime: '90s',
        videoUrl: 'https://www.youtube.com/watch?v=2yjwXTZQDDI',
        description: 'Extensión completa sobre la cabeza.',
        order: 4,
        dayOfWeek: 1,
      },
      {
        id: 'ex-fb-5',
        name: 'Plancha Abdominal Isometrica',
        sets: 3,
        reps: 45,
        restTime: '45s',
        videoUrl: 'https://www.youtube.com/watch?v=pSHjTRCQxIw',
        description: 'Tensión constante en el core.',
        order: 5,
        dayOfWeek: 1,
      },
    ],
  },
  {
    name: 'Rutina Torso - Pierna Hipertrofia (4 Días)',
    difficulty: 'intermediate',
    description: 'División clásico Torso/Pierna frecuencia 2 para maximizar masa muscular e intensidad.',
    isPreset: true,
    source: 'system',
    exercises: [
      {
        id: 'ex-tp-1',
        name: 'Press de Banca Plano con Barra',
        sets: 4,
        reps: 8,
        restTime: '90s',
        videoUrl: 'https://www.youtube.com/watch?v=rT7DgCr-3pg',
        description: 'Enfocado en fuerza e hipertrofia pectoral.',
        order: 1,
        dayOfWeek: 1,
      },
      {
        id: 'ex-tp-2',
        name: 'Dominadas Pronadas',
        sets: 4,
        reps: 8,
        restTime: '90s',
        videoUrl: 'https://www.youtube.com/watch?v=eGo4IYlbE5g',
        description: 'Barba sobre la barra en cada repetición.',
        order: 2,
        dayOfWeek: 1,
      },
      {
        id: 'ex-tp-3',
        name: 'Press Inclinado con Mancuernas',
        sets: 3,
        reps: 10,
        restTime: '75s',
        videoUrl: 'https://www.youtube.com/watch?v=8iPEnn-ltC8',
        description: 'Aislamiento de pecho superior.',
        order: 3,
        dayOfWeek: 1,
      },
      {
        id: 'ex-tp-4',
        name: 'Elevaciones Laterales con Mancuernas',
        sets: 4,
        reps: 15,
        restTime: '60s',
        videoUrl: 'https://www.youtube.com/watch?v=3VcKaXpzqRo',
        description: 'Deltoides lateral.',
        order: 4,
        dayOfWeek: 1,
      },
      {
        id: 'ex-tp-5',
        name: 'Sentadilla Trasera con Barra (Back Squat)',
        sets: 4,
        reps: 8,
        restTime: '120s',
        videoUrl: 'https://www.youtube.com/watch?v=ultWZbUMPL8',
        description: 'Día de Pierna heavy.',
        order: 1,
        dayOfWeek: 2,
      },
      {
        id: 'ex-tp-6',
        name: 'Peso Muerto Rumano (RDL)',
        sets: 4,
        reps: 10,
        restTime: '90s',
        videoUrl: 'https://www.youtube.com/watch?v=JCXUYuzwNrM',
        description: 'Cadena posterior e isquiotibiales.',
        order: 2,
        dayOfWeek: 2,
      },
    ],
  },
  {
    name: 'Push / Pull / Legs Avanzado (6 Días)',
    difficulty: 'advanced',
    description: 'Esquema de empuje, tirón y pierna de alta frecuencia e intensidad para atletas experimentados.',
    isPreset: true,
    source: 'system',
    exercises: [
      {
        id: 'ex-ppl-1',
        name: 'Press de Banca Plano con Barra',
        sets: 4,
        reps: 6,
        restTime: '120s',
        videoUrl: 'https://www.youtube.com/watch?v=rT7DgCr-3pg',
        description: 'Día Push: Carga pesada.',
        order: 1,
        dayOfWeek: 1,
      },
      {
        id: 'ex-ppl-2',
        name: 'Press Militar de Pie con Barra',
        sets: 4,
        reps: 8,
        restTime: '90s',
        videoUrl: 'https://www.youtube.com/watch?v=2yjwXTZQDDI',
        description: 'Empuje deltoides.',
        order: 2,
        dayOfWeek: 1,
      },
      {
        id: 'ex-ppl-3',
        name: 'Peso Muerto Convencional',
        sets: 4,
        reps: 6,
        restTime: '120s',
        videoUrl: 'https://www.youtube.com/watch?v=op9kVnSso6Q',
        description: 'Día Pull: Tirón pesado.',
        order: 1,
        dayOfWeek: 2,
      },
      {
        id: 'ex-ppl-4',
        name: 'Dominadas Pronadas',
        sets: 4,
        reps: 8,
        restTime: '90s',
        videoUrl: 'https://www.youtube.com/watch?v=eGo4IYlbE5g',
        description: 'Dorsal ancho.',
        order: 2,
        dayOfWeek: 2,
      },
      {
        id: 'ex-ppl-5',
        name: 'Sentadilla Trasera con Barra (Back Squat)',
        sets: 4,
        reps: 6,
        restTime: '120s',
        videoUrl: 'https://www.youtube.com/watch?v=ultWZbUMPL8',
        description: 'Día Legs: Cuadriceps.',
        order: 1,
        dayOfWeek: 3,
      },
      {
        id: 'ex-ppl-6',
        name: 'Hip Thrust con Barra en Banco',
        sets: 4,
        reps: 10,
        restTime: '90s',
        videoUrl: 'https://www.youtube.com/watch?v=LM8XHLYJoYs',
        description: 'Hipertrofia de glúteo.',
        order: 2,
        dayOfWeek: 3,
      },
    ],
  },
  {
    name: 'Cardio & Core HIIT Fat-Burner (3 Días)',
    difficulty: 'intermediate',
    description: 'Plan de alta intensidad para quema de grasa y acondicionamiento físico metabólico.',
    isPreset: true,
    source: 'system',
    exercises: [
      {
        id: 'ex-hiit-1',
        name: 'Sprints HIIT en Cinta o Pista',
        sets: 8,
        reps: 30,
        restTime: '60s',
        videoUrl: 'https://www.youtube.com/watch?v=cZnsLVArIt8',
        description: '30s sprint máximo + 60s descanso activo.',
        order: 1,
        dayOfWeek: 1,
      },
      {
        id: 'ex-hiit-2',
        name: 'Plancha Abdominal Isometrica',
        sets: 4,
        reps: 60,
        restTime: '45s',
        videoUrl: 'https://www.youtube.com/watch?v=pSHjTRCQxIw',
        description: 'Resistencia abdominal.',
        order: 2,
        dayOfWeek: 1,
      },
      {
        id: 'ex-hiit-3',
        name: 'Rueda Abdominal (Ab-Wheel Rollout)',
        sets: 3,
        reps: 12,
        restTime: '60s',
        videoUrl: 'https://www.youtube.com/watch?v=rqiTPdK1c_I',
        description: 'Anti-extensión lumbar.',
        order: 3,
        dayOfWeek: 1,
      },
    ],
  },
];
